[profile.release]
opt-level = "s"

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "codegen-units=8", "-C", "debuginfo=0", "-C", "profile-generate", "-C", "inline-threshold=2000"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "codegen-units=8", "-C", "debuginfo=0", "-C", "profile-generate", "-C", "inline-threshold=2000"]

[target.i686-pc-windows-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "codegen-units=4", "-C", "debuginfo=0", "-C", "profile-generate", "-C", "inline-threshold=2000"]

[target.i686-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "codegen-units=4", "-C", "debuginfo=0", "-C", "profile-generate", "-C", "inline-threshold=2000"]